[package]
name = "bio-streams"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"

[dev-dependencies]
flate2 = "1.0"
clap = { version="4", features=["derive"] }

[[example]]
name = "fqcheck"
