[package]
name = "bio-streams"
version = "0.2.2"
edition = "2021"

[dependencies]
futures = "0.3"
bio-seq = "0.10"

[dev-dependencies]
flate2 = "1.0"
clap = { version="4", features=["derive"] }
bio-seq = "0.10"
#bio-seq = { path="../bio-seq" }

[[example]]
name = "fqcheck"

[[example]]
name = "aminokmers"
